drop table if exists courses;
create table courses (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  latitude double,
  longitude double,
  county varchar(255),
  municipality varchar(255),
  holes integer,
  external_id varchar(255) unique
);
insert into courses (name, external_id) values ('Gammel Bane', 'osm-legacy');
