app.frontend.url=http://localhost:3000

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./data/golfjakten
spring.datasource.username=sa
spring.datasource.password=

server.servlet.session.cookie.secure=false

spring.config.import=optional:classpath:secrets.properties
